# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/worbb/Desktop/Electronics/LCSE/PIC/PIC.srcs/sources_1/ip/clk_ip/clk_ip.xci
# IP: The module: 'clk_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/worbb/Desktop/Electronics/LCSE/PIC/PIC.gen/sources_1/ip/clk_ip/clk_ip_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/worbb/Desktop/Electronics/LCSE/PIC/PIC.gen/sources_1/ip/clk_ip/clk_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/worbb/Desktop/Electronics/LCSE/PIC/PIC.gen/sources_1/ip/clk_ip/clk_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/worbb/Desktop/Electronics/LCSE/PIC/PIC.srcs/sources_1/ip/clk_ip/clk_ip.xci
# IP: The module: 'clk_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/worbb/Desktop/Electronics/LCSE/PIC/PIC.gen/sources_1/ip/clk_ip/clk_ip_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/worbb/Desktop/Electronics/LCSE/PIC/PIC.gen/sources_1/ip/clk_ip/clk_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/worbb/Desktop/Electronics/LCSE/PIC/PIC.gen/sources_1/ip/clk_ip/clk_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
